feat: support skipping u-boot install
Support skipping u-boot install for boards that support booting from
u-boot residing in SPI flash.

Signed-off-by: Louis SCHNEIDER <louis@schne.id>
Signed-off-by: Noel Georgi <git@frezbo.dev>

diff --git a/artifacts/rock5b/u-boot/pkg.yaml b/artifacts/rock5b/u-boot/pkg.yaml
--- a/artifacts/rock5b/u-boot/pkg.yaml
+++ b/artifacts/rock5b/u-boot/pkg.yaml
@@ -9,6 +9,7 @@ dependencies:
   - stage: arm-trusted-firmware-rk3588
   - stage: rkbin-rk3588
     platform: linux/amd64
+
 steps:
   - sources:
       - url: https://ftp.denx.de/pub/u-boot/u-boot-{{ .uboot_rk1_version }}.tar.bz2
@@ -20,16 +21,18 @@ steps:
     prepare:
       # rock-5b-rk3588
       - |
-        mkdir -p /usr/bin \
-          && ln -sf /toolchain/bin/env /usr/bin/env \
-          && ln -sf /toolchain/bin/python3 /toolchain/bin/python
+        mkdir -p /usr/bin
+        ln -sf /toolchain/bin/env /usr/bin/env
+        ln -sf /toolchain/bin/python3 /toolchain/bin/python
 
-        pip3 install pyelftools setuptools \
-          && ln -sf /toolchain/bin/python3 /toolchain/bin/python
+        pip3 install pyelftools setuptools
 
         tar xf u-boot.tar.bz2 --strip-components=1
 
-        patch -p1 < /pkg/patches/uboot-byteorder.patch
+        for patch in $(find /pkg/patches -type f -name "*.patch" | sort); do
+          echo "Applying $patch"
+          patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
+        done
       - |
         make rock5b-rk3588_defconfig
     build:
@@ -38,7 +41,7 @@ steps:
     install:
       - |
         mkdir -p /rootfs/artifacts/arm64/u-boot/rock5b
-        cp u-boot-rockchip.bin /rootfs/artifacts/arm64/u-boot/rock5b
+        cp -v -t /rootfs/artifacts/arm64/u-boot/rock5b u-boot-rockchip.bin u-boot-rockchip-spi.bin
 finalize:
   - from: /rootfs
     to: /rootfs
