feat: add support for orange pi 5 max
added support for Orange Pi 5 Max
updated uboot_rk1 version to 2025.07 -- needed for Orange Pi 5 Max
updated Orange Pi 5 Plus patches and Turing rk1 patches due to the newer uboot_rk1

Signed-off-by: alardev <14848618+alardev@users.noreply.github.com>
Signed-off-by: Noel Georgi <git@frezbo.dev>
Signed-off-by: Paul Robertson <me@perobertson.com>
Signed-off-by: Noel Georgi <git@frezbo.dev>

diff --git a/artifacts/orangepi-5-max/u-boot/pkg.yaml b/artifacts/orangepi-5-max/u-boot/pkg.yaml
--- a/artifacts/orangepi-5-max/u-boot/pkg.yaml
+++ b/artifacts/orangepi-5-max/u-boot/pkg.yaml
@@ -1,7 +1,7 @@
 # References:
 #   U-Boot:
 #     - https://u-boot.readthedocs.io/en/latest
-name: u-boot-rock5a
+name: u-boot-orangepi-5-max
 variant: scratch
 shell: /bin/bash
 dependencies:
@@ -17,19 +17,23 @@ steps:
     env:
       SOURCE_DATE_EPOCH: {{ .BUILD_ARG_SOURCE_DATE_EPOCH }}
     prepare:
-      # rock-5a-rk3588s
+      # orangepi-5-max-rk3588
       - |
-
         tar xf u-boot.tar.bz2 --strip-components=1
+
+        for patch in $(find /pkg/patches -type f -name "*.patch" | sort); do
+          echo "Applying $patch"
+          patch -p1 < $patch || (echo "Failed to apply patch $patch" && exit 1)
+        done
       - |
-        make rock5a-rk3588s_defconfig
+        make orangepi-5-max-rk3588_defconfig
     build:
       - |
         make -j $(nproc) HOSTLDLIBS_mkimage="-lssl -lcrypto" BL31=/libs/arm-trusted-firmware/rk3588/bl31.elf ROCKCHIP_TPL=/libs/rkbin/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.19.bin
     install:
       - |
-        mkdir -p /rootfs/artifacts/arm64/u-boot/rock5a
-        cp u-boot-rockchip.bin /rootfs/artifacts/arm64/u-boot/rock5a
+        mkdir -p /rootfs/artifacts/arm64/u-boot/orangepi-5-max
+        cp -v -t /rootfs/artifacts/arm64/u-boot/orangepi-5-max u-boot-rockchip.bin u-boot-rockchip-spi.bin
 finalize:
   - from: /rootfs
     to: /rootfs
